# Generated by Django 4.2 on 2023-09-23 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_file_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='username',
            new_name='usern',
        ),
    ]
